# Chapter 6 - Computational Algorithms in Linear Algebra

This notebook contains code accompanying Chapter 6 Computational Algorithms in Linear Algebra in *Practical Discrete Mathematics* by Ryan T. White and Archana Tikayat Ray.

## Matrices and Matrix Representations of Linear Systems

The code below stores matrices as `NumPy` arrays and prints specified entries of the matrices.

In [2]:
import numpy 

# initialize matrices 
A = numpy.array([[3, 2, 1], [9, 0, 1], [3, 4, 1]]) 
B = numpy.array([[1, 1, 2], [8, 4, 1], [0, 0, 3]])

# print the entry in the first row and first column of A
print(A[0,0])

# print the entry in the second row and third column of B
print(B[1,2])

3
1


### Example: Matrix Addition and Subtraction

In [3]:
# Add A and B
print(numpy.add(A,B))

# Subtract A and B
print(numpy.subtract(A,B))

[[ 4  3  3]
 [17  4  2]
 [ 3  4  4]]
[[ 2  1 -1]
 [ 1 -4  0]
 [ 3  4 -2]]


### Example: Scalar Multiplication and Transpose

In [8]:
# Multiply A by a scalar 5
print(numpy.multiply(5,A))

# Find the transpose of A
print(numpy.transpose(A))

[[15 10  5]
 [45  0  5]
 [15 20  5]]
[[3 9 3]
 [2 0 4]
 [1 1 1]]


### Example: Matrix Multiplication and Transpose

In [9]:
# Multiply A and B
print(numpy.dot(A,B))

[[19 11 11]
 [ 9  9 21]
 [35 19 13]]


## Solving Large Linear Systems with `NumPy`

### Example: Solving $\mathbf{Ax}=\mathbf{b}$ for $\mathbf{x}$

In [10]:
import numpy

# Create A and b matrices
A = numpy.array([[2, -6, 6], [2, 3, -1], [4, -3, -1]])
b = numpy.array([-8, 15, 19])

# Solve Ax = b
numpy.linalg.solve(A,b)


array([ 5.,  1., -2.])

### Example: Inconsistent and Dependent Systems with `NumPy`

In [14]:
import numpy

# inconsistent system
A = numpy.array([[2, 1], [6, 3]])
b = numpy.array([3, 3])

print(numpy.linalg.solve(A,b))

LinAlgError: Singular matrix

Note that the code throws an error because the matrix $\mathbf{A}$ is singular since the system is inconsistent--i.e. there are no solutions.

In [19]:
# dependent system
A = numpy.array([[2, 1], [6, 3]])
b = numpy.array([1, 3])

print(numpy.linalg.solve(A,b))

LinAlgError: Singular matrix

Note that the code throws an error because the matrix $\mathbf{A}$ is singular since the system is dependent--i.e. there are infinitely many solutions, as we can confirm below.

In [20]:
A = numpy.array([[2, 1], [6, 3]])
print(numpy.linalg.det(A))

0.0


### Example: 10-by-10 Linear System (with `NumPy`)

In [21]:
import numpy

numpy.random.seed(1)

# Create A and b matrices with random
A = 10*numpy.random.rand(10,10)-5
b = 10*numpy.random.rand(10)-5

# Solve Ax = b
solution = numpy.linalg.solve(A,b)
print(solution)

# To verify the solution works, show Ax - b is near 0
sum(abs(numpy.dot(A,solution) - b))

[ 0.09118027 -1.51451319 -2.48186344 -2.94076307  0.07912968  2.76425416
  2.48851394 -0.30974375 -1.97943716  0.75619575]


2.1538326677728037e-14